name: cloudflare_warp_panel
description: A graphical panel for Cloudflare WARP on Linux.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  bitsdojo_window: ^0.1.5 # Adicionado para personalização da janela

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/zero-trust-connected.svg
    - assets/zero-trust-connected-exclamation.svg
    - assets/zero-trust-disconnected.svg
    - assets/zero-trust-error.svg
    - assets/zero-trust-orange.svg