name: cloudflare_warp_panel
description: A graphical panel for Cloudflare WARP on Linux.
version: 5.0.1+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  bitsdojo_window: ^0.1.5
  url_launcher: ^6.1.14
  package_info_plus: ^5.0.1 # Pacote para ler a versão do app
  shared_preferences: ^2.2.3
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/zero-trust-connected.svg
    - assets/zero-trust-connected-exclamation.svg
    - assets/zero-trust-disconnected.svg
    - assets/zero-trust-error.svg
    - assets/zero-trust-orange.svg
    - assets/cloudflare-logo.svg
    - assets/zero-trust-connecting.svg
